typo
build:dev:watch requires a development.json file, not development.js

Causes the error "[webpack-cli] Error: Cannot find module './config/development.json'" otherwise.